name: flutter_gauges
description: Flutter gauges library to create interactive and animated gauges.
version: 17.4.50-beta

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.15.0 <0.17.0"

flutter: